# Generated by Django 5.2.4 on 2026-02-03 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='applications_count',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='salary_max',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='salary_min',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='salary_type',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='views_count',
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='community',
            field=models.CharField(choices=[('business', 'Business Class Community'), ('working', 'Working Class Community')], default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired')], default='active', max_length=20),
        ),
        migrations.DeleteModel(
            name='OpportunityApplication',
        ),
    ]
