# Generated by Django 5.2.4 on 2026-02-05 20:23

import django.core.validators
import django.db.models.deletion
import giving.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drives', '0007_remove_drivecontribution_message'),
        ('partners', '0009_remove_partnerrequest_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GivingStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_type', models.CharField(choices=[('quarterly', 'Quarterly'), ('annual', 'Annual'), ('custom', 'Custom Range')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('file', models.FileField(blank=True, null=True, upload_to='giving_statements/')),
                ('file_url', models.URLField(blank=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_count', models.PositiveIntegerField()),
                ('summary_data', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('downloaded_count', models.PositiveIntegerField(default=0)),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_statements', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giving_statements', to='partners.partner')),
            ],
            options={
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledGiving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('giving_type', models.CharField(choices=[('weekly-partnership', 'Weekly Partnership'), ('radio-broadcast', 'Radio Broadcast Support'), ('youth-camp', 'Youth Camp Support'), ('bible-distribution', 'Bible Distribution'), ('fellowship', 'Fellowship Support'), ('ministry-support', 'General Ministry Support'), ('drive-contribution', 'Drive Contribution'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('frequency', models.CharField(choices=[('one-time', 'One Time'), ('weekly', 'Weekly'), ('bi-weekly', 'Bi-Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], max_length=50)),
                ('payment_method', models.CharField(choices=[('mobile-money', 'Mobile Money'), ('bank-transfer', 'Bank Transfer'), ('credit-card', 'Credit Card'), ('cash', 'Cash'), ('cheque', 'Cheque')], max_length=50)),
                ('start_date', models.DateField()),
                ('next_payment_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scheduled_givings', to=settings.AUTH_USER_MODEL)),
                ('drive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_givings', to='drives.drive')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_givings', to='partners.partner')),
            ],
            options={
                'ordering': ['next_payment_date'],
            },
        ),
        migrations.CreateModel(
            name='Giving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(default=giving.models.generate_giving_transaction_id, editable=False, max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('giving_type', models.CharField(choices=[('weekly-partnership', 'Weekly Partnership'), ('radio-broadcast', 'Radio Broadcast Support'), ('youth-camp', 'Youth Camp Support'), ('bible-distribution', 'Bible Distribution'), ('fellowship', 'Fellowship Support'), ('ministry-support', 'General Ministry Support'), ('drive-contribution', 'Drive Contribution'), ('other', 'Other')], default='ministry-support', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='completed', max_length=20)),
                ('date', models.DateField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('mobile-money', 'Mobile Money'), ('bank-transfer', 'Bank Transfer'), ('credit-card', 'Credit Card'), ('cash', 'Cash'), ('cheque', 'Cheque')], default='mobile-money', max_length=50)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('frequency', models.CharField(choices=[('one-time', 'One Time'), ('weekly', 'Weekly'), ('bi-weekly', 'Bi-Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], default='one-time', max_length=50)),
                ('next_payment_date', models.DateField(blank=True, null=True)),
                ('schedule_end_date', models.DateField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('receipt_sent', models.BooleanField(default=False)),
                ('receipt_sent_at', models.DateTimeField(blank=True, null=True)),
                ('drive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giving_transactions', to='drives.drive')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='givings', to='partners.partner')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_givings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-recorded_at'],
                'indexes': [models.Index(fields=['partner', 'date'], name='giving_givi_partner_9016f1_idx'), models.Index(fields=['status', 'date'], name='giving_givi_status_4b3cca_idx')],
            },
        ),
        migrations.CreateModel(
            name='GivingGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], default='monthly', max_length=20)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giving_goals', to='partners.partner')),
            ],
            options={
                'ordering': ['-start_date'],
                'unique_together': {('partner', 'period', 'start_date')},
            },
        ),
    ]
