# Generated by Django 5.2.4 on 2026-02-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giving', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giving',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='giving',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='scheduledgiving',
            name='description',
        ),
        migrations.RemoveField(
            model_name='scheduledgiving',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='scheduledgiving',
            name='payment_method',
        ),
        migrations.AlterField(
            model_name='giving',
            name='frequency',
            field=models.CharField(choices=[('one-time', 'One Time'), ('weekly', 'Weekly'), ('bi-weekly', 'Bi-Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='one-time', max_length=50),
        ),
        migrations.AlterField(
            model_name='giving',
            name='giving_type',
            field=models.CharField(choices=[('weekly-partnership', 'Weekly Partnership'), ('spirit-world', 'Spirit World'), ('saturday-fellowship', 'Saturday Fellowship'), ('office-rent', 'Office Rent'), ('drive', 'Drive')], default='weekly-partnership', max_length=50),
        ),
        migrations.AlterField(
            model_name='scheduledgiving',
            name='frequency',
            field=models.CharField(choices=[('one-time', 'One Time'), ('weekly', 'Weekly'), ('bi-weekly', 'Bi-Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], max_length=50),
        ),
        migrations.AlterField(
            model_name='scheduledgiving',
            name='giving_type',
            field=models.CharField(choices=[('weekly-partnership', 'Weekly Partnership'), ('spirit-world', 'Spirit World'), ('saturday-fellowship', 'Saturday Fellowship'), ('office-rent', 'Office Rent'), ('drive', 'Drive')], max_length=50),
        ),
    ]
