# Generated by Django 5.2.4 on 2026-03-03 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giving', '0002_remove_giving_notes_remove_giving_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giving',
            name='description',
        ),
        migrations.RemoveField(
            model_name='giving',
            name='title',
        ),
    ]
