# Generated by Django 5.2.4 on 2026-03-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giving', '0003_remove_giving_description_remove_giving_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='giving',
            name='payment_method',
            field=models.CharField(choices=[('mobile-money', 'Mobile Money'), ('bank-transfer', 'Bank Transfer'), ('cash', 'Cash'), ('check', 'Check'), ('other', 'Other')], default='mobile-money', max_length=50),
        ),
    ]
