# Generated by Django 5.2.4 on 2026-03-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giving', '0005_alter_giving_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giving',
            name='payment_method',
            field=models.CharField(choices=[('mobile-money', 'Mobile Money'), ('bank-transfer', 'Bank Transfer'), ('debit-card', 'Debit Card'), ('cash', 'Cash'), ('cheque', 'Cheque')], default='mobile-money', max_length=50),
        ),
    ]
