# Generated by Django 5.2.4 on 2026-03-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giving', '0006_alter_giving_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giving',
            name='giving_type',
            field=models.CharField(choices=[('weekly-partnership', 'Weekly Partnership'), ('spirit-world', 'Spirit World'), ('saturday-fellowship', 'Saturday Fellowship'), ('office-rent', 'Office Rent'), ('drive', 'Drive'), ('prophetic-offering', 'Prophetic Offering'), ('love-offering', 'Love Offering')], default='weekly-partnership', max_length=50),
        ),
        migrations.AlterField(
            model_name='scheduledgiving',
            name='giving_type',
            field=models.CharField(choices=[('weekly-partnership', 'Weekly Partnership'), ('spirit-world', 'Spirit World'), ('saturday-fellowship', 'Saturday Fellowship'), ('office-rent', 'Office Rent'), ('drive', 'Drive'), ('prophetic-offering', 'Prophetic Offering'), ('love-offering', 'Love Offering')], max_length=50),
        ),
    ]
