# Generated by Django 5.2.4 on 2026-02-09 20:43

import django.core.validators
import django.db.models.deletion
import weekly_budget.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0010_partnergoal_alter_partner_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category_type', models.CharField(choices=[('ministry', 'Ministry Operations'), ('outreach', 'Outreach & Evangelism'), ('media', 'Media & Production'), ('facilities', 'Facilities & Maintenance'), ('staff', 'Staff Support'), ('missions', 'Missions & Travel'), ('resources', 'Resources & Materials'), ('other', 'Other Expenses')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('default_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Default percentage allocation', max_digits=5)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Budget Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_id', models.CharField(default=weekly_budget.models.generate_weekly_budget_id, editable=False, max_length=100, unique=True)),
                ('title', models.CharField(default='Ministry Weekly Budget', max_length=200)),
                ('year', models.IntegerField()),
                ('week_number', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('upcoming', 'Upcoming'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('is_published', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_weekly_budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Weekly Budget',
                'verbose_name_plural': 'Weekly Budgets',
                'ordering': ['-year', '-week_number'],
                'unique_together': {('year', 'week_number')},
            },
        ),
        migrations.CreateModel(
            name='BudgetContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.TextField(blank=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('contribution_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('contributed_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('payment_method', models.CharField(choices=[('mobile-money', 'Mobile Money'), ('bank-transfer', 'Bank Transfer'), ('cash', 'Cash'), ('other', 'Other')], default='mobile-money', max_length=50)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to='weekly_budget.budgetcategory')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_contributions', to='partners.partner')),
                ('weekly_budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='weekly_budget.weeklybudget')),
            ],
            options={
                'ordering': ['-contributed_at'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyBudgetStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('week_number', models.IntegerField()),
                ('total_target', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_raised', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_contributions', models.IntegerField(default=0)),
                ('total_partners', models.IntegerField(default=0)),
                ('category_breakdown', models.JSONField(blank=True, default=dict)),
                ('previous_week_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('week_over_week_change', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('generated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', '-week_number'],
                'unique_together': {('year', 'week_number')},
            },
        ),
        migrations.CreateModel(
            name='BudgetBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, help_text='Percentage of total budget allocated to this category', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_breakdowns', to='weekly_budget.budgetcategory')),
                ('weekly_budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakdown_items', to='weekly_budget.weeklybudget')),
            ],
            options={
                'ordering': ['-percentage'],
                'unique_together': {('weekly_budget', 'category')},
            },
        ),
    ]
