# Generated by Django 5.2.4 on 2026-03-31 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklybudget',
            options={'ordering': ['-start_date'], 'verbose_name': 'Weekly Budget', 'verbose_name_plural': 'Weekly Budgets'},
        ),
        migrations.AlterUniqueTogether(
            name='weeklybudget',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='weeklybudget',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20),
        ),
        migrations.RemoveField(
            model_name='weeklybudget',
            name='description',
        ),
        migrations.RemoveField(
            model_name='weeklybudget',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='weeklybudget',
            name='published_at',
        ),
        migrations.RemoveField(
            model_name='weeklybudget',
            name='week_number',
        ),
        migrations.RemoveField(
            model_name='weeklybudget',
            name='year',
        ),
    ]
