# Generated by Django 5.2.4 on 2025-08-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_testimony'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='picture',
            field=models.ImageField(default='blog_images/prophet_namara_logo.png', upload_to='blog_images/'),
        ),
    ]
