# Generated by Django 5.2.4 on 2025-08-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_testimony_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(default='Faith & Spirituality', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='comments',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='read_time',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
