# Generated by Django 5.2.4 on 2025-08-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpost_category_blogpost_comments_blogpost_likes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='picture',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(default='Faith', max_length=100),
        ),
    ]
