# Generated by Django 5.2.4 on 2025-08-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_picture_blogpost_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimony',
            old_name='snippet',
            new_name='quote',
        ),
        migrations.RemoveField(
            model_name='testimony',
            name='author',
        ),
        migrations.RemoveField(
            model_name='testimony',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='testimony',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='testimony',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='testimony',
            name='title',
        ),
        migrations.AddField(
            model_name='testimony',
            name='image',
            field=models.ImageField(default='blog_images/prophet_namara_logo.png', upload_to='testimonies/'),
        ),
        migrations.AddField(
            model_name='testimony',
            name='name',
            field=models.CharField(default='Peter Wisdom', max_length=255),
        ),
        migrations.AddField(
            model_name='testimony',
            name='role',
            field=models.CharField(default='CEO', max_length=255),
        ),
    ]
