# Generated by Django 5.2.4 on 2026-02-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_heroslide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('Blog', 'Blog'), ('Partners', 'Partners')], default='Blog', max_length=50),
        ),
    ]
