# Generated by Django 5.2.4 on 2025-08-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediafiles', '0002_audio_description_audio_is_active_video_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='drive_url',
        ),
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='embed_id',
            field=models.CharField(default='dQw4w9WgXcQ', max_length=50),
        ),
        migrations.AddField(
            model_name='video',
            name='views',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('Prophecy', 'Prophecy'), ('Testimony', 'Testimony'), ('Christmas Message', 'Christmas Message'), ('Sunday Service', 'Sunday Service'), ('Teaching', 'Teaching')], default='Prophecy', max_length=50),
        ),
    ]
