# Generated by Django 5.2.4 on 2025-08-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediafiles', '0003_remove_video_drive_url_video_duration_video_embed_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='embed_id',
            field=models.CharField(default='dQw4w9WgXcQ', max_length=255),
        ),
    ]
