# Generated by Django 5.2.4 on 2025-08-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediafiles', '0004_alter_video_embed_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='embed_id',
            field=models.CharField(default='dQw4w9WgXcQ', max_length=50),
        ),
    ]
