# Generated by Django 5.2.4 on 2025-08-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediafiles', '0005_video_source_url_alter_video_embed_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('Prophecy', 'Prophecy'), ('Testimony', 'Testimony'), ('Christmas Message', 'Christmas Message'), ('Sunday Service', 'Sunday Service')], default='Prophecy', max_length=50),
        ),
    ]
