# Generated by Django 5.2.4 on 2025-08-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediafiles', '0006_alter_video_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='source_url',
            field=models.URLField(blank=True, default='https://www.youtube.com/embed/V85KJHciV9M?si=WBM1m9aOIXI-_5qf'),
        ),
    ]
