# Generated by Django 5.2.4 on 2025-08-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediafiles', '0007_alter_video_source_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='audio',
            old_name='date_posted',
            new_name='date',
        ),
        migrations.AddField(
            model_name='audio',
            name='speaker',
            field=models.CharField(default='Prophet Namara Ernest', max_length=255),
        ),
    ]
