# Generated by Django 5.2.4 on 2025-08-12 11:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediafiles', '0008_rename_is_active_audio_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='speaker',
            field=models.CharField(default='Prophet Namara Ernest', editable=False, max_length=255),
        ),
    ]
