# Generated by Django 5.2.4 on 2025-12-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediafiles', '0009_alter_audio_date_alter_audio_speaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='original_url',
            field=models.URLField(default='https://youtu.be/h9fDRNOlDMM?si=7rDFj-ZW5pkvEagb'),
        ),
        migrations.AlterField(
            model_name='video',
            name='embed_id',
            field=models.CharField(default='h9fDRNOlDMM', max_length=50),
        ),
        migrations.AlterField(
            model_name='video',
            name='source_url',
            field=models.URLField(blank=True, default='https://www.youtube.com/embed/h9fDRNOlDMM'),
        ),
    ]
