# Generated by Django 5.2.4 on 2025-12-04 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediafiles', '0010_video_original_url_alter_video_embed_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='video',
            name='views',
        ),
    ]
