# Generated by Django 5.2.4 on 2025-12-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediafiles', '0011_remove_video_duration_remove_video_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='original_url',
            field=models.URLField(default='https://drive.google.com/file/d/1CtcO2nRbULMYMoI4QuWNBt5m8yibF_sC/view?usp=sharing'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='drive_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
