# Generated by Django 5.2.4 on 2026-02-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediafiles', '0012_audio_original_url_alter_audio_drive_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='category',
            field=models.CharField(choices=[('Spirit_World', 'Spirit World'), ('Partners', 'Partners')], default='Spirit_World', max_length=50),
        ),
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('Prophecy', 'Prophecy'), ('Testimony', 'Testimony'), ('Partners', 'Partners')], default='Prophecy', max_length=50),
        ),
    ]
