# Generated by Django 5.2.4 on 2026-09-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediafiles', '0013_audio_category_alter_video_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livestream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_url', models.URLField(blank=True)),
                ('is_live', models.BooleanField(default=False)),
                ('next_broadcast_at', models.DateTimeField(blank=True, null=True)),
                ('offline_message', models.TextField(blank=True)),
            ],
        ),
    ]
