# Generated by Django 5.2.4 on 2025-08-06 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_remove_partnerapplication_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PartnerApplication',
            new_name='Partner',
        ),
    ]
