# Generated by Django 5.2.4 on 2025-08-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_rename_partnerapplication_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='message',
            field=models.TextField(default='I am committing to UGX 100,000 weekly'),
        ),
    ]
