# Generated by Django 5.2.4 on 2025-08-14 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_partner_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='last_name',
            new_name='lastName',
        ),
    ]
