# Generated by Django 5.2.4 on 2026-01-03 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_rename_first_name_partner_firstname_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['-joined_at'], 'verbose_name': 'Partner', 'verbose_name_plural': 'Partners'},
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='submitted_at',
            new_name='joined_at',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='email',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='message',
        ),
        migrations.AddField(
            model_name='partner',
            name='commitment_note',
            field=models.TextField(blank=True, help_text='Stated giving commitment or notes'),
        ),
        migrations.AddField(
            model_name='partner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='partner',
            name='phone',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='PartnerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=30)),
                ('message', models.TextField(help_text='Reason / intent to partner')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_partner_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partner Request',
                'verbose_name_plural': 'Partner Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
