# Generated by Django 5.2.4 on 2026-01-03 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0007_partnerinvite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partnerrequest',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='partnerrequest',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='partnerinvite',
            name='partner_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invite', to='partners.partnerrequest'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='commitment_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='partnerrequest',
            name='message',
            field=models.TextField(),
        ),
    ]
