# Generated by Django 5.2.4 on 2026-01-03 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0008_rename_firstname_partnerrequest_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerrequest',
            name='message',
        ),
    ]
