# Generated by Django 5.2.4 on 2026-02-05 23:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0009_remove_partnerrequest_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('financial', 'Financial'), ('spiritual', 'Spiritual'), ('service', 'Service'), ('community', 'Community')], default='financial', max_length=50)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deadline', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_active', 'deadline'],
            },
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['-joined_at']},
        ),
        migrations.AddField(
            model_name='partner',
            name='avatar_color',
            field=models.CharField(default='from-purple-600 to-purple-400', max_length=50),
        ),
        migrations.AddField(
            model_name='partner',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='community',
            field=models.CharField(choices=[('working', 'Working Class Community'), ('business', 'Business Community Partner')], default='working', max_length=50),
        ),
        migrations.AddField(
            model_name='partner',
            name='last_active',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='member_since',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='organization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='partner_type',
            field=models.CharField(choices=[('individual', 'Individual Partner'), ('company', 'Business Partner')], default='individual', max_length=50),
        ),
        migrations.AddField(
            model_name='partner',
            name='total_given',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='partnerinvite',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partnerinvite',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AddConstraint(
            model_name='partner',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_partner_per_user'),
        ),
        migrations.AddField(
            model_name='partnergoal',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='partners.partner'),
        ),
    ]
