# Generated by Django 5.2.4 on 2026-02-09 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0010_partnergoal_alter_partner_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='avatar_color',
        ),
    ]
