# Generated by Django 5.2.4 on 2026-02-09 21:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0010_partnergoal_alter_partner_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('category_type', models.CharField(choices=[('product', 'Product'), ('service', 'Service'), ('need', 'Need')], default='product', max_length=20)),
                ('icon_name', models.CharField(blank=True, max_length=50)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Marketplace Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('listing_type', models.CharField(choices=[('product', 'Product'), ('service', 'Service'), ('need', 'Need')], max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('pending', 'Pending'), ('sold', 'Sold/Completed'), ('unavailable', 'Unavailable'), ('removed', 'Removed')], default='available', max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(choices=[('UGX', 'Ugandan Shilling'), ('USD', 'US Dollar'), ('KES', 'Kenyan Shilling'), ('TZS', 'Tanzanian Shilling')], default='UGX', max_length=10)),
                ('is_price_negotiable', models.BooleanField(default=False)),
                ('is_free', models.BooleanField(default=False)),
                ('location', models.CharField(max_length=255)),
                ('is_location_flexible', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='marketplace/listings/')),
                ('image_url', models.URLField(blank=True)),
                ('contact_method', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('message', 'In-App Message')], max_length=20)),
                ('contact_info', models.CharField(blank=True, max_length=255)),
                ('contact_visible', models.BooleanField(default=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('saves_count', models.PositiveIntegerField(default=0)),
                ('inquiries_count', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_urgent', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='marketplace.marketplacecategory')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_listings', to='partners.partner')),
            ],
            options={
                'ordering': ['-is_featured', '-posted_date'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_likes', to='partners.partner')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='marketplace.marketplacelisting')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('contact_method', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('message', 'In-App Message')], max_length=20)),
                ('contact_info', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('responded', 'Responded'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inquirer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_inquiries', to='partners.partner')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='marketplace.marketplacelisting')),
            ],
            options={
                'verbose_name_plural': 'Marketplace Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam or misleading'), ('fraud', 'Fraud or scam'), ('inappropriate', 'Inappropriate content'), ('prohibited', 'Prohibited item'), ('wrong_category', 'Wrong category'), ('other', 'Other')], max_length=50)),
                ('details', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='marketplace.marketplacelisting')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_reports', to='partners.partner')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_marketplace_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='marketplace.marketplacelisting')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_saves', to='partners.partner')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='marketplacelisting',
            index=models.Index(fields=['listing_type', 'status'], name='marketplace_listing_bb6007_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplacelisting',
            index=models.Index(fields=['category', 'status'], name='marketplace_categor_8ff0c6_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplacelisting',
            index=models.Index(fields=['partner', 'status'], name='marketplace_partner_c5cb13_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='marketplacelike',
            unique_together={('listing', 'partner')},
        ),
        migrations.AlterUniqueTogether(
            name='marketplacereport',
            unique_together={('listing', 'reporter')},
        ),
        migrations.AlterUniqueTogether(
            name='marketplacesave',
            unique_together={('listing', 'partner')},
        ),
    ]
