# Generated by Django 5.2.4 on 2026-02-02 10:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0009_remove_partnerrequest_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.CharField(help_text='Brief description for cards', max_length=300)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('category', models.CharField(choices=[('evangelism', 'Evangelism Outreach'), ('construction', 'Building/Construction'), ('education', 'Education/Schools'), ('medical', 'Medical Missions'), ('relief', 'Disaster Relief'), ('children', 'Children Ministry'), ('youth', 'Youth Programs'), ('media', 'Media/Production'), ('other', 'Other')], max_length=50)),
                ('goal_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='drives/')),
                ('color_scheme', models.CharField(choices=[('purple', 'Purple'), ('blue', 'Blue'), ('green', 'Green'), ('orange', 'Orange'), ('red', 'Red')], default='purple', max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_urgent', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('contributions_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_drives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriveContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('is_anonymous', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('contribution_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('contributed_at', models.DateTimeField(auto_now_add=True)),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='drives.drive')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_contributions', to='partners.partner')),
            ],
            options={
                'ordering': ['-contributed_at'],
            },
        ),
        migrations.CreateModel(
            name='DriveUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('update_type', models.CharField(choices=[('progress', 'Progress Update'), ('milestone', 'Milestone Reached'), ('story', 'Impact Story'), ('need', 'Urgent Need'), ('general', 'General Update')], default='progress', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='drive_updates/')),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_updates', to=settings.AUTH_USER_MODEL)),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='drives.drive')),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='drive',
            index=models.Index(fields=['status', 'is_published'], name='drives_driv_status_1e889b_idx'),
        ),
        migrations.AddIndex(
            model_name='drive',
            index=models.Index(fields=['category', 'is_featured'], name='drives_driv_categor_24e1dc_idx'),
        ),
        migrations.AddIndex(
            model_name='drivecontribution',
            index=models.Index(fields=['drive', 'contributed_at'], name='drives_driv_drive_i_fccbbe_idx'),
        ),
        migrations.AddIndex(
            model_name='drivecontribution',
            index=models.Index(fields=['partner', 'contributed_at'], name='drives_driv_partner_622e21_idx'),
        ),
    ]
