# Generated by Django 5.2.4 on 2026-02-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drives', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drive',
            name='image',
        ),
        migrations.RemoveField(
            model_name='drive',
            name='short_description',
        ),
        migrations.AlterField(
            model_name='drive',
            name='category',
            field=models.CharField(choices=[('saturday_fellowship', 'Saturday Fellowship'), ('spirit_world', 'Spirit World'), ('office_rent', 'Office Rent'), ('other', 'Other')], max_length=50),
        ),
    ]
