# Generated by Django 5.2.4 on 2026-02-02 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drives', '0002_remove_drive_image_remove_drive_short_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivecontribution',
            name='message',
        ),
    ]
