# Generated by Django 5.2.4 on 2026-02-02 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drives', '0003_remove_drivecontribution_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='driveupdate',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driveupdate',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_drive_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driveupdate',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
