# Generated by Django 5.2.4 on 2026-02-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drives', '0004_driveupdate_approved_at_driveupdate_approved_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driveupdate',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='driveupdate',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='driveupdate',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='drivecontribution',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
