# Generated by Django 5.2.4 on 2026-02-02 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drives', '0005_remove_driveupdate_approved_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driveupdate',
            name='image',
        ),
    ]
