# Generated by Django 5.2.4 on 2026-02-02 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drives', '0006_remove_driveupdate_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivecontribution',
            name='message',
        ),
    ]
