# Generated by Django 5.2.4 on 2026-04-01 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('action_type', models.CharField(choices=[('drive_created', 'New Drive Created'), ('drive_updated', 'Drive Updated'), ('opportunity_created', 'New Opportunity Added'), ('opportunity_updated', 'Opportunity Updated'), ('budget_created', 'New Weekly Budget'), ('budget_updated', 'Budget Updated'), ('marketplace_listing', 'New Marketplace Listing'), ('marketplace_inquiry', 'New Marketplace Inquiry'), ('giving_received', 'New Giving Received'), ('schedule_created', 'New Schedule Created'), ('partner_joined', 'New Partner Joined')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_activities', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='core_activi_recipie_b3e0a8_idx'), models.Index(fields=['is_public', '-created_at'], name='core_activi_is_publ_e241da_idx')],
            },
        ),
    ]
